@startuml
hide circles

Title <b>Client</b>\n<size:12>Authors: Feng Guan, Chris Ocker</size>


class "SquireServer" as ss

class "UserAccount" as ua {
-DisplayName
-Username
-IsHost
-Bio
-Photo
-FirstName
-LastName
-Email
-Online
-Password
+RegisterRequest()
+PasswordReset()
+ChangeStatus()
+JoinProject()
+LeaveProject()
+UpdateProfile()
}

class "SquireClient" as sc {
+GetFromUser()
+GetFromServer()
+SendToUser()
+SendToServer()
}


class "FriendsList" as fl {
-FriendCount
-FriendArray
+FriendRequest()
+CheckOnline()
+FriendAccept()
+InviteToChat()
}


sc "1"  -- "1" ua : Manages >
ss "1"  -- "*" sc : Communicates
fl  -r-* ua
@enduml

