@startuml
hide circles

Title <b>Client</b>\n<size:12>Authors: Feng Guan, Chris Ocker</size>


class "SquireServer" as ss

class "UserAccount" as ua {
-DisplayName
-UserID
+LoginRequest()
+LogoutRequest()
+RegisterRequest()
}

class "SquireClient" as sc {
+GetRequest()
+SendRequest()
}

class "UserInfo" as ui {
-Username
-IsHost
-Bio
-Photo
}

class "FriendsList" as fl {
-FriendCount
-FriendArray
+FriendRequest()
}


sc "1"  -- "1" ua : Manages >
ss "1"  -- "*" sc : Communicates
ss      -- ua : Assigns\nUser ID >
ui "1"  -right-*   ua 
fl "1"  -left-* ua
@enduml

