@startuml
hide circle
hide empty members

Title <b>Server - User Update Info</b>\n

class "AccountManager" as uam
class "UserUpdateInfo" as uaui{
	-ValidationToken
	+UserID
	+UserInfoKeyValuePairs
	+ValidateUser()
	}

uam - uaui : <<Argument>>


@enduml