@startuml
hide circle
hide empty members

Title <b>Server - File</b>\n

class "Project" as sqs_pr
class "File" as sqs_fi{
	-FileID
	-FileName
	-FileDescription
	-FileContent
	+GetFileInfo()
	+UpdateFile(Key,Value)
	}

sqs_pr o-- "*" sqs_fi 

@enduml