@startuml
hide circle
hide empty members

Title <b>Server - Session Manager</b>\n

class "Server" as sqs
class "SessionManager" as sqs_se_m{
	-SessionList
	+CreateSession()
	+CloseSession()
	+GetSession(SessionID)
	}
class "Session" as sqs_se


sqs *-- "1" sqs_se_m 
sqs_se_m o-- "*" sqs_se


@enduml