@startuml
hide circle
hide empty members

Title <b>Chat</b>\n<size:12>Authors: Grant Wade, Jesse Jutson\n<size:12>Reviewed by: Scott Dennis


class "ServerChatManager" as chat{
	+chatroomList
	+createRoom(name)

}

class "Chatroom" as chatroom{
	+id
	+addMessage(msg)
	+getMessages()
	+sendMessagesToClients()
}

/'
class "Chat Message" as chatMsg{
	+fromUsername
	+text
	+timestamp
}
'/


class "ClientChatManager" as clientChat{
	-lastReceiveTime - epoch time for the last time messages were received
	-joinedChannels - list of all the channels user is part of. dynamic

	-parseMessages( ) - called by fetchMessages()
	+fetchMessages()
	+sendMessage(toChannel, message)
	+getJoinedChannelList()
	+joinChannel(channelName)
	+leaveChannel(channelName)
}

class "ChatroomView" as clientChatroom{
	+id
	+sendMessage()
	+displayMessage()
}


class "Message" as msg{
'	+fromID
	+fromUsername
	+text
	+timestamp
}


class "UserAccount" as userAccount{
	-userInfo
	+getUserID()
}


chat  o-- "*" chatroom : manages
chatroom  o-- "*" msg : keeps

clientChat  o-- "*" clientChatroom : manages
userAccount  -up-  clientChat : provides user info >
clientChatroom  o-- "*" msg : displays

'projectChat -r-|> clientChatroom

clientChat "*" -r- chat : fetches messages >

@enduml