/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tim' at '3/29/16 6:49 PM' with Gradle 2.9
 *
 * @author Tim, @date 3/29/16 6:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
