@startuml
hide circle
hide empty members

Title <b>Server - File Update Info</b>\n

class "Project" as sqp
class "FileUpdateInfo" as sqfui{
	+FileID
	+FileEditKeyValuePairs
	}

sqp - sqfui : <<Argument>>

@enduml