@startuml
hide circle
hide empty members

Title <b>Project Update Info</b>\n<size:12>Authors: ferg2065, </size>

class "ProjectManager" as sqpm
class "ProjectUpdateInfo" as sqpui{
	+ProjectID
	+ProjectEditKeyValuePairs
	}

sqpm - sqpui : Encapsulates User Changes


@enduml