@startuml
hide circle
hide empty members

Title <b>Session</b>\n<size:12>Authors: ferg2065, </size>

class "SessionManager" as sqs_se_m
class "Session" as sqs_se{
	+Socket
	+SessionID
	+UserID
	+ProjectID
	+ChatIDs
	}

			
sqs_se_m *-- "*" sqs_se


@enduml