@startuml
hide circle
hide empty members

Title <b>File</b>\n<size:12>Authors: ferg2065, </size>

class "Project" as sqs_pr
class "File" as sqs_fi{
	-FileID
	-FileName
	-FileDescription
	-FileContent
	+GetFileInfo()
	+UpdateFile(Key,Value)
	}

sqs_pr *-- "*" sqs_fi 

@enduml