@startuml
hide circle
hide empty members

Title <b>Server - Session</b>\n

class "SessionManager" as sqs_se_m
class "Session" as sqs_se{
	+Socket
	+SessionID
	+UserID
	+ProjectID
	+ChatIDs
	}

sqs_se_m o-- "*" sqs_se


@enduml