@startuml
hide circle
hide empty members

Title <b>Server - Project Update Info</b>\n

class "ProjectManager" as sqpm
class "ProjectUpdateInfo" as sqpui{
	+ProjectID
	+ProjectEditKeyValuePairs
	}

sqpm - sqpui : Encapsulates User Changes


@enduml