@startuml
hide circle
hide empty members

Title <b>File Update Info</b>\n<size:12>Authors: ferg2065, </size>

class "Project" as sqp
class "FileUpdateInfo" as sqfui{
	+FileID
	+FileEditKeyValuePairs
	}


sqp - sqfui : <<Argument>>

@enduml