@startuml
hide circle
hide empty members

class "Client" as sq

class "Server" as sqs

	class "AccountManager" as sqs_acc
		
	class "ProjectManager" as sqs_proj

	class "ChatManager" as sqs_chat

	class "DBConnector" as sqs_dbc

sq -right- sqs : <<JSONS over TCP>>
 
sqs *-- sqs_acc
sqs *-- sqs_proj
sqs *-- sqs_chat
sqs *-- sqs_dbc

sqs_dbc -u- sqs_acc :Sends info
sqs_dbc -u- sqs_proj :Sends info
sqs_dbc -u- sqs_chat :Sends info



@enduml