@startuml
hide circle
hide empty members

class "Client" as sq

class "Server" as sqs{
	AccountManager
	ProjectManager
	Sockets
	SendChatMessage(GUIDs)
	AccountManagerMethods()
	ProjectManagerMethods()
	}

class "AccountManager" as uam{
	'AccountList
	'CreateAccount(Name, Email)
	'Login(LoginInfo)
	'Logout(UserGUID)
	'GetUserDetails(Name)
	'SetUserDetails(UserUpdateInfo)
	}
class "ProjectManager" as sqpm{
	'ProjectList
	'CreateProject(Name)
	'OpenProject(Name)
	'DeleteProject(Name)
	'UpdateProject(ProjectUpdateInfo)
	}

sq -right- sqs : <<TCP>>

sqs *-- sqpm : 1
sqs *-- uam : 1









@enduml