@startuml
hide circle
hide empty members

class "Server" as sqs	
class "Server Account" as ua
class "Client" as sq	
class "Project" as sqp 
class "File" as sqf 
class "Chat" as chat 
class "Global Chat" as gchat 
class "Project Chat" as pchat 
class "Private Chat" as fchat 
class "Backend" as bkg

sq -right- sqs : <<TCP>>

sqs *-- sqp : Many
sqs *-- ua : Many
sqs *-- chat : 1
sqs *-- bkg

chat *-- gchat
chat *-- pchat
chat *-- fchat

'sqp *-left- ua : Many
sqp *-- sqf : 0..*

@enduml