@startuml
hide circle
hide empty members

class "Client" as sq 
class "Server" as sqs{
	-AccountManager
	-ProjectManager
	-SessionManager
	-ChatManager
	+AccountManagerMethods()
	+ProjectManagerMethods()
	+SessionManagerMethods()
	+ChatManagerMethods(GUIDs)
	}
	class "AccountManager" as sqs_ua_m{
		-AccountList
		+CreateAccount(Name, Email)
		+Login(LoginInfo)
		+Logout(UserID)
		+GetUserDetails(Name)
		+SetUserDetails(UserUpdateInfo)
		}
		class "UserAccount" as sqs_ua {
			+first_name
			+last_name
			+user_name
			-password
			+register()
			+login()
			+logout()
			}
	class "ProjectManager" as sqs_pr_m{
		-ProjectList
		+CreateProject(Name)
		+OpenProject(Name)
		+DeleteProject(Name)
		+GetProject(Name)
		+GetProject(ProjectID)
		+UpdateProject(ProjectUpdateInfo)
		}
		class "Project" as sqs_pr{
			-ProjectID
			-ProjectDescription
			-ProjectSettings
			-FileIDs
			-OwnerUserIDs
			+GetProjectID()
			+GetProjectDescription()
			+GetProjectSettings()
			+GetProjectFiles()
			+GetProjectOwners()
			+UpdateProject(Key,Value)
			+UpdateFile(FileUpdateInfo)
			}
			class "File" as sqs_fi{
				-FileID
				-FileName
				-FileDescription
				-FileContent
				+GetFileInfo()
				+UpdateFile(Key,Value)
				}
	class "SessionManager" as sqs_se_m{
		-SessionList
		+CreateSession()
		+CloseSession()
		+GetSession(SessionID)
		}
		class "Session" as sqs_se{
			+Socket
			+SessionID
			+UserID
			+ProjectID
			+ChatIDs
			}
	class "ChatManager" as sqs_ch_m{
		+chatroomList
		+createRoom(name)
		}
		class "ChatRoom" as sqs_ch {
			+id
			+addMessage(msg)
			+getMessages()
			+sendMessagesToClients()
			}
			class "ChatMessage" as sqs_ch_mes{
				+fromID
				+text
				+timestamp
				}


sq -right- sqs : <<TCP>>

	sqs *-- "1" sqs_pr_m 
		sqs_pr_m o-- "*" sqs_pr 
			sqs_pr o-- "*" sqs_fi 
	sqs *-- "1" sqs_ua_m 
		sqs_ua_m o-- "*" sqs_ua  
	sqs *-- "1" sqs_ch_m 
		sqs_ch_m o-- "*" sqs_ch 
			sqs_ch o-- "*" sqs_ch_mes
	sqs *-- "1" sqs_se_m 
		sqs_se_m o-- "*" sqs_se



@enduml