@startuml

class "User Account Manager" as UAM {
f_name: String
l_name: String
user_name: String
password: String
email: String

login()
registration()
logout()
password_reset()
}


class "User" as U {
f_name: String
l_name: String
user_name: String
password: String
email: String


}

class "Registration" as R {
f_name: String
l_name: String
user_name: String
password: String
email: String

set_name()
set_user_name()
set_password()
set_email()
}


class "Login" as login {
user_name: String
password: String

check_name_pass(user_name, password)
}
U "*"-d-* UAM 
login -r- UAM
R -l- UAM 
@enduml
