@startuml

class "SquireAccount" as ua {
first_name
last_name
user_name
password
register()
login()
logout()
}



class "Register" as re {
first_name
last_name
user_name
password

check_username()
check_password()
}

@enduml
