@startuml

class "sQuire Account" as ua {
first_name
last_name
user_name
password
register()
login()
logout()
}



class "Register" as re {
first_name
last_name
user_name
password

get_username()
get_password()
get_first_last_name()
check_username()
check_password()
}

class "Login" as lo {
user_name
password

check_username()
check_password()
}









@enduml
