@startuml
hide circle
hide empty members

class "Client" as sq_c

class "ProjectManager" as sq_projmgr {
    -userTracker : UserTracker
    -editQueue : EditQueue
    +updateToServer()
}

class "Server" as sq_server

class "Project" as proj {
    -owners : UserAccount[]
    -participants : UserAccount[]
    -isOnline : boolean
    -onlineUsers : UserAccount[]
    -lastUpdated : String
    +downloadProjectPackage()
    +importProjectPackage()
}

class "UserTracker" as projmgr_utrack {
    -loc : Location
    -focus : String
    +update()
}

class "EditQueue" as projmgr_editq {
    -edits : AtomicEdit[]
    +enqueueEdit()
    +pushEditsToServer(Server server)
}

class "AtomicEdit" as editq_atomedit {
    -type : String
    -loc : Location
    -val : Object
    +packForTransport() : TCPPacket
}

class "Location" as loc {
    -file : String
    -lineNumber : int
    -lineColumn : int
    -length : int
    +set(String file, int line, int col, int len)
}

sq_c o-- "1" sq_projmgr

sq_projmgr o-left- "1" sq_server : Communicates With over TCP

sq_projmgr -- "1" projmgr_utrack : Track User
sq_projmgr o-- "1" projmgr_editq : Log Edits
sq_projmgr o-- "0..*" proj

projmgr_editq o-- "0..*" editq_atomedit : Stores and Sends

projmgr_utrack o-- "1" loc
projmgr_utrack -- editq_atomedit : Generates

editq_atomedit o-- "1" loc



@enduml