@startuml
hide circle
hide empty members

title <b>Client</b>\n<size:12>Authors: slip5295, denn2725</size>

class "Client" as sq_c {
    -clientAccountManager : ClientAccountManager
    -projectManager : ProjectManager
    -chatManager : Chat Manager
    -server : Server
    -gui : GUI
    +sendChatMessageToServer()
    +getProjectsFromServer() : Project[]
    +sendProjectUpdateToServer()
    +displayGUI()
    +
}


class "ClientAccountManager" as sq_acntmgr 
class "ProjectManager" as sq_projmgr
class "ChatManager" as sq_chatmgr
class "Server" as sq_server
class "GUI" as sq_gui

sq_c -left- sq_server : Communicates With\nServer Over TCP

sq_c *-- sq_projmgr
sq_c *-- sq_acntmgr
sq_c *-- sq_chatmgr
sq_c *-- sq_gui


@enduml