@startuml

Actor User
User -> GUI : Register
activate GUI
GUI -> LoginPaneController : register
activate LoginPaneController
LoginPaneController -> Client : reg(Usr, Email, Pwd)
activate Client
Client -> Server : SendInstruction(Reg, (Usr, Email, Pwd))
activate Server
Server --> Client : Success
deactivate Server
Client --> LoginPaneController :Success
LoginPaneController --> GUI : Success
deactivate LoginPaneController
GUI --> User :You are registered!
Client -> AccountManager : Update Profile
activate AccountManager
AccountManager -> UserAccount : StoreData(Usr, Email, Pwd)
deactivate AccountManager
activate UserAccount
UserAccount --> AccountManager :Success
deactivate UserAccount
activate AccountManager
AccountManager --> Client :Success
deactivate AccountManager



@enduml