@startuml

Actor User
activate Client
User -> Client : Register
Client -> AccountManager : RequestAction(AM,Register)
activate AccountManager
AccountManager --> Client : Register(UsrNm,Pswd,Eml)
deactivate AccountManager
Client -> User : GetFromUser(UsrNm,Pswd,Eml)
User --> Client : UsrNm,Pswd,Eml
Client -> Server : SendToServer(Register,UsrNm,Pswd,Eml)
activate Server
Server --> Client : SendToClient(Success)
deactivate Server
Client -> AccountManager : RequestAction(AM,StoreData,UsrNm,Pswd,Eml)
activate AccountManager
AccountManager -> UserAccount : StoreData(UsrNm,Pswd,Eml)
deactivate AccountManager
activate UserAccount
UserAccount --> AccountManager : Success
deactivate UserAccount
activate AccountManager
AccountManager --> Client : Success
deactivate AccountManager
Client --> User : OutputToUser("Registration Successful")

@enduml