@startuml
hide circle
hide empty members

Title <b>Chat</b>\n<size:12>Authors: juts3869\n

actor User
User -> ChatRoomView : Hits send
activate ChatRoomView
ChatRoomView -> ClientChatManager: sendMessage(string, channel)
activate ClientChatManager
ClientChatManager -> Server : sendMessages(message[])
activate Server
Server -> ClientChatManager : success
deactivate Server
ClientChatManager -> ChatRoomView : success


ClientChatManager -> Server: updateMessages(message[])

activate Server
Server -> ClientChatManager : message[]
deactivate Server
ClientChatManager -> ChatRoomView : message[]
ChatRoomView -> User : Displays Message

@enduml
