@startuml

Title <b>Send Chat Message</b>\n<size:12>Author: juts3869\n

actor User
participant ChatRoomView as CRV
participant ClientChatManager as CCM
participant Message as M
participant UserAccount as UA
participant Server as S

activate CRV
User -> CRV : Types and hits send
CRV -> CCM: sendMessage(string, channel)
activate CCM
CCM -> M : Message(string, channel)
activate M
M -> UA : getUserID()
activate UA
UA --> M : UserID
deactivate UA
M --> CCM : message
deactivate M
CCM -> S : sendMessage(message)
activate S
S --> CCM : success
deactivate S
CCM --> CRV : success
deactivate CCM


'/CCM -> S: updateMessages(message)
'/activate S
'/S --> CCM : message[]
'/deactivate S
'/CCM --> CRV : message[]
CRV --> User : Displays Message

@enduml
