DROP TABLE FileEdits;
DROP TABLE ProjectAccess;
DROP TABLE PFiles;
DROP TABLE PDirs;
DROP TABLE PFLines;
DROP TABLE Projects;
DROP TABLE Subscriptions;
DROP TABLE Messages;
DROP TABLE Channels;
DROP TABLE Users;
DROP PROCEDURE PFLTraverser;

