@startuml

left to right direction

:User: as user


rectangle Chat {
(Enter Chat Room) as chat_enterRoom
(Leave Chat Room) as chat_leaveRoom
(Send Chat Message) as chat_sendMessage
(Custom Chat Room) as chat_customRoom
}

rectangle Server {
(Create User Account on Server) as s_createAccount
(Authenticate user and Create Session) as s_authSession
(Create Project) as s_createProject
}

rectangle Client {
(Import Code) as c_importCode
(Export Code) as c_exportCode
(Compile) as c_compile
(Execute) as c_execute
(Open Project) as c_openProject
(Exit Project) as c_exitProject
}

rectangle Editor {
(View File Text by User Edits) as e_viewUser
(Edit Code) as e_editCode
}

rectangle "User Accounts" {
(Reset Password) as ua_resetPassword
(Create Account) as ua_createAccount
(Check Status) as ua_checkStatus
(Account Log In) as ua_login
(Account Log Out) as ua_logout
(Project Access Request) as ua_projectRequest
(Project Access Accepted) as ua_projectAccept
(Project Access Declined) as ua_projectDecline
}

user --> chat_enterRoom
user --> chat_leaveRoom
user --> chat_sendMessage
user --> chat_customRoom

user --> s_createAccount
user --> s_authSession
user --> s_createProject

user --l-> c_importCode
user --l-> c_exportCode
user --l-> c_compile
user --l-> c_execute
user --l-> c_openProject
user --l-> c_exitProject

user --> e_viewUser
user --> e_editCode

user --l-> ua_resetPassword
user --l-> ua_createAccount
user --l-> ua_checkStatus
user --l-> ua_login
user --l-> ua_logout
user --l-> ua_projectRequest
user --l-> ua_projectAccept
user --l-> ua_projectDecline

@enduml