@startuml

title <b>Join Project</b>\n<size:12>Author: slip5295</size>

Actor User
Activate User


User -> Client : joinProject()
'Deactivate User
Activate Client
Client -> Server : getProjectList()
Deactivate Client
Activate Server
Server --> Client : projectList
Deactivate Server
Activate Client
Client --> User : projectList
Deactivate Client
Activate User

User -> Client : selectProject()
Deactivate User
Activate Client
Client -> ProjectManager : setProject()
Deactivate Client
Activate ProjectManager
ProjectManager -> Project : downloadProject()
Deactivate ProjectManager
Activate Project
Project -> Server : requestProject()
Deactivate Project
Activate Server
Server --> Project : projectPackage
Deactivate Server
Activate Project
Project -> Project : createFileStructure()
Project --> ProjectManager : finished
Deactivate Project
Activate ProjectManager
ProjectManager --> Client : projectReady
Deactivate ProjectManager
Activate Client
Client --> User : projectJoined
Deactivate Client
'Activate User







@enduml